# Site settings
title: postops
description: 'cat /dev/random > blog'
url: 'http://postops.co'
baseurl: ''
# google_analytics: 'UA-79833253-1'
disqus_shortname: 'postops'

jekyll-crosspost_to_medium:
  text: "<p><i>This article was originally posted <a href=\"#{url}\" rel=\"canonical\">on postops</a>.</i></p>"

author:
  name: 'Jay Wallace'
  twitter_username: mootpt
  # facebook_username: cantc
  medium_username: postops
  github_username:  mootpt
  linkedin_username:  cantc
  keybase_username: nullpt

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate','jekyll-gist','jekyll-crosspost-to-medium']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
