version: 2
jobs:
  build:
    working_directory: ~/postops
    docker:
      - image: ruby:latest
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: 'apt-get -y update'
      - run:
          name: Install nodejs
          command: 'apt-get -y install nodejs'
      - run:
          name: Bundle install
          command: 'bundle install'
      - run:
          name: Jekyll Build
          command: 'jekyll build'
      - run:
          name: Push up cross-post cache
          command: './scripts/push_cache.sh'
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
